export const EstadoSubastaConstants = {

    RECAUDACIONENPROCESO: 67,
    RECAUDACIONCANCELADA: 68,
    PROCESADACONFONDOS: 69,
    PROCESADASINFONDOS: 70,
    PROCESADACONFONDOSMINNIMOS: 71,
    APROBADACONFONDOSMINIMOS: 72,
    CANCELADACONFONDOSMINIMOS: 73
};